### ISSUE TITLE
Laravel v6

### ISSUE THREAD

**Issue by benrolfe** [rebing/timber-laravel#5]
Will this package work with Laravel v6? Composer is giving me this error:

`rebing/timber-laravel v1.2.0 requires illuminate/support ~5`

**Comment by benrolfe** [comment]
@rebing Also, will it work on **Laravel 7**? I now get this error:

`rebing/timber-laravel v1.2.2 requires illuminate/support 5.5.*|5.6.*|5.7.*|5.8.*|^6.0`

Thanks.
Ben

**Comment by rebing** [comment]
@benrolfe Hi sorry, I have not tested. Can you test and create a PR please?

**Comment by benrolfe** [comment]
@rebing I've created a PR. See https://github.com/rebing/timber-laravel/pull/6
